import { Product } from '../Product'
export const data : Product[] = [
  {
    id: 1,
    name:  "Laptop Asus Vivobook",
    price:  25.99,
    desc: "Laptop mỏng nhẹ, chơi tốt game online, GTA 5 màn hình 15.6 Inch Full HD",
    img: "http://placehold.it/700x400",
    status: true,
    show1:"Laptop Asus Vivobook",
    show2: "Giá: $25.99",
    show3: "Laptop mỏng nhẹ, chơi tốt game online, GTA 5 màn hình 15.6 Inch Full HD",
    show4: "CPU: AMD Ryzen 5 3500U",
    show5: "RAM: 8GB",
    show6: "Ổ cứng: SSD 256GB ",
    show7: "VGA: AMD Radeon Vega 8"
  },

  {
    id: 2,
    name:  "Laptop Dell Precision M4800 Intel Core i7 MQ",
    price:  25.99,
    desc: "Là một Designer thì không thể bỏ qua siêu phẩm Dell Precision M4800 bởi:",
    img: "http://placehold.it/700x400",
    status: true,
    show1:"Laptop Dell Precision M4800",
    show2: "Giá: $25.99",
    show3: "Laptop mỏng nhẹ, chLà một Designer thì không thể bỏ qua siêu phẩm Dell Precision M4800 bởi:Cấu hình mạnh mẽ giúp máy làm tốt 2D, 3D trên các phần mềm như AutoCad, Sketchup, Revit...hay dựng 3D, render file nặng chơi tốt game online, GTA 5 màn hình 15.6 Inch Full HD",
    show4: "CPU: i7 - 4800MQ",
    show5: "RAM: 8GB",
    show6: "Ổ cứng: SSD 256GB ",
    show7: "VGA: Card rời AMD FirePro M5100"
  },

    {
    id: 3,
    name:  "Laptop Dell Precision 7510 - Intel Core i7",
    price:  25.99,
    desc: "Dell Precision 7510: Đẹp hơn, khỏe hơn Dell Precision M4800",
    img: "http://placehold.it/700x400",
    status: true,
        show1:"Laptop Dell Precision 7510",
    show2: "Giá: $25.99",
    show3: "Laptop mỏng nhẹ, chLà một Designer thì không thể bỏ qua siêu phẩm Dell Precision M4800 bởi:Cấu hình mạnh mẽ giúp máy làm tốt 2D, 3D trên các phần mềm như AutoCad, Sketchup, Revit...hay dựng 3D, render file nặng chơi tốt game online, GTA 5 màn hình 15.6 Inch Full HD",
    show4: "CPU: Intel Core i7 6820HQ",
    show5: "RAM: 8GB",
    show6: "Ổ cứng: SSD 256GB ",
    show7: "VGA: Nvidia Quadro M1000"
  },

    {
    id: 4,
    name:  "Laptop Asus Vivobook",
    price:  25.99,
    desc: "Laptop mỏng nhẹ, chơi tốt game online, GTA 5 màn hình 15.6 Inch Full HD",
    img: "http://placehold.it/700x400",
    status: true,
    show1:"Laptop Asus Vivobook",
    show2: "Giá: $25.99",
    show3: "Laptop mỏng nhẹ, chơi tốt game online, GTA 5 màn hình 15.6 Inch Full HD",
    show4: "CPU: AMD Ryzen 5 3500U",
    show5: "RAM: 8GB",
    show6: "Ổ cứng: SSD 256GB ",
    show7: "VGA: AMD Radeon Vega 8"
  },
    {
    id: 5,
    name:  "Laptop Dell Precision M4800 Intel Core i7 MQ",
    price:  25.99,
    desc: "Là một Designer thì không thể bỏ qua siêu phẩm Dell Precision M4800 bởi:",
    img: "http://placehold.it/700x400",
    status: true,
    show1:"Laptop Dell Precision M4800",
    show2: "Giá: $25.99",
    show3: "Laptop mỏng nhẹ, chLà một Designer thì không thể bỏ qua siêu phẩm Dell Precision M4800 bởi:Cấu hình mạnh mẽ giúp máy làm tốt 2D, 3D trên các phần mềm như AutoCad, Sketchup, Revit...hay dựng 3D, render file nặng chơi tốt game online, GTA 5 màn hình 15.6 Inch Full HD",
    show4: "CPU: i7 - 4800MQ",
    show5: "RAM: 8GB",
    show6: "Ổ cứng: SSD 256GB ",
    show7: "VGA: Card rời AMD FirePro M5100"
  }, 
   {
    id: 6,
    name:  "Laptop Dell Precision 7510 - Intel Core i7",
    price:  25.99,
    desc: "Dell Precision 7510: Đẹp hơn, khỏe hơn Dell Precision M4800",
    img: "http://placehold.it/700x400",
    status: true,
        show1:"Laptop Dell Precision 7510",
    show2: "Giá: $25.99",
    show3: "Laptop mỏng nhẹ, chLà một Designer thì không thể bỏ qua siêu phẩm Dell Precision M4800 bởi:Cấu hình mạnh mẽ giúp máy làm tốt 2D, 3D trên các phần mềm như AutoCad, Sketchup, Revit...hay dựng 3D, render file nặng chơi tốt game online, GTA 5 màn hình 15.6 Inch Full HD",
    show4: "CPU: Intel Core i7 6820HQ",
    show5: "RAM: 8GB",
    show6: "Ổ cứng: SSD 256GB ",
    show7: "VGA: Nvidia Quadro M1000"
   },
    {
    id: 7,
    name:  "Laptop Asus Vivobook",
    price:  25.99,
    desc: "Laptop mỏng nhẹ, chơi tốt game online, GTA 5 màn hình 15.6 Inch Full HD",
    img: "http://placehold.it/700x400",
    status: true,
    show1:"Laptop Asus Vivobook",
    show2: "Giá: $25.99",
    show3: "Laptop mỏng nhẹ, chơi tốt game online, GTA 5 màn hình 15.6 Inch Full HD",
    show4: "CPU: AMD Ryzen 5 3500U",
    show5: "RAM: 8GB",
    show6: "Ổ cứng: SSD 256GB ",
    show7: "VGA: AMD Radeon Vega 8"
  },
    {
    id: 8,
    name:  "Laptop Dell Precision M4800 Intel Core i7 MQ",
    price:  25.99,
    desc: "Là một Designer thì không thể bỏ qua siêu phẩm Dell Precision M4800 bởi:",
    img: "http://placehold.it/700x400",
    status: true,
    show1:"Laptop Dell Precision M4800",
    show2: "Giá: $25.99",
    show3: "Laptop mỏng nhẹ, chLà một Designer thì không thể bỏ qua siêu phẩm Dell Precision M4800 bởi:Cấu hình mạnh mẽ giúp máy làm tốt 2D, 3D trên các phần mềm như AutoCad, Sketchup, Revit...hay dựng 3D, render file nặng chơi tốt game online, GTA 5 màn hình 15.6 Inch Full HD",
    show4: "CPU: i7 - 4800MQ",
    show5: "RAM: 8GB",
    show6: "Ổ cứng: SSD 256GB ",
    show7: "VGA: Card rời AMD FirePro M5100"
  },
    {
    id: 9,
   name:  "Laptop Dell Precision 7510 - Intel Core i7",
    price:  25.99,
    desc: "Dell Precision 7510: Đẹp hơn, khỏe hơn Dell Precision M4800",
    img: "http://placehold.it/700x400",
    status: true,
        show1:"Laptop Dell Precision 7510",
    show2: "Giá: $25.99",
    show3: "Laptop mỏng nhẹ, chLà một Designer thì không thể bỏ qua siêu phẩm Dell Precision M4800 bởi:Cấu hình mạnh mẽ giúp máy làm tốt 2D, 3D trên các phần mềm như AutoCad, Sketchup, Revit...hay dựng 3D, render file nặng chơi tốt game online, GTA 5 màn hình 15.6 Inch Full HD",
    show4: "CPU: Intel Core i7 6820HQ",
    show5: "RAM: 8GB",
    show6: "Ổ cứng: SSD 256GB ",
    show7: "VGA: Nvidia Quadro M1000"
  },
    {
    id: 10,
    name:  "Laptop Asus Vivobook",
    price:  25.99,
    desc: "Laptop mỏng nhẹ, chơi tốt game online, GTA 5 màn hình 15.6 Inch Full HD",
    img: "http://placehold.it/700x400",
    status: true,
    show1:"Laptop Asus Vivobook",
    show2: "Giá: $25.99",
    show3: "Laptop mỏng nhẹ, chơi tốt game online, GTA 5 màn hình 15.6 Inch Full HD",
    show4: "CPU: AMD Ryzen 5 3500U",
    show5: "RAM: 8GB",
    show6: "Ổ cứng: SSD 256GB ",
    show7: "VGA: AMD Radeon Vega 8"
  },
]